server:
  port: 13848
spring:
  datasource:
    username: root
    password: czc123
    url: jdbc:mysql:///czc_security
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 1